#!/usr/bin/env bash
#
# Deploy the pipeline to Azure Container Instances.
#
#   ./deploy/azure/deploy.sh          build images and deploy
#   ./deploy/azure/deploy.sh logs     tail the running group
#   ./deploy/azure/deploy.sh status   show state and the public URLs
#   ./deploy/azure/deploy.sh destroy  delete the whole resource group
#
# Names are generated once and cached in deploy/azure/.azure-env so re-running
# updates the same deployment instead of creating a second one.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/deploy/azure/.azure-env"
TEMPLATE="$REPO_ROOT/deploy/azure/aci.template.yaml"
GENERATED="$REPO_ROOT/deploy/azure/aci.generated.yaml"

LOCATION="${LOCATION:-australiaeast}"   # closest region to Wellington

# Cache the generated names so a second run targets the first deployment.
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
else
  SUFFIX="$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  RESOURCE_GROUP="${RESOURCE_GROUP:-team9-signals-rg}"
  ACR_NAME="${ACR_NAME:-team9signals${SUFFIX}}"        # must be globally unique
  GROUP_NAME="${GROUP_NAME:-team9-signals}"
  DNS_LABEL="${DNS_LABEL:-team9-signals-${SUFFIX}}"    # must be unique per region
fi

TAG="${TAG:-latest}"

say()  { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
fail() { printf '\n\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

require_login() {
  az account show >/dev/null 2>&1 || fail "not logged in — run: az login"
}

save_env() {
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — delete this file to start a fresh deployment.
RESOURCE_GROUP=$RESOURCE_GROUP
ACR_NAME=$ACR_NAME
GROUP_NAME=$GROUP_NAME
DNS_LABEL=$DNS_LABEL
LOCATION=$LOCATION
EOF
}

cmd_deploy() {
  require_login
  say "Subscription: $(az account show --query name -o tsv)"
  say "Region $LOCATION · resource group $RESOURCE_GROUP · registry $ACR_NAME"

  az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
  save_env

  if ! az acr show --name "$ACR_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
    say "Creating container registry $ACR_NAME"
    az acr create \
      --resource-group "$RESOURCE_GROUP" \
      --name "$ACR_NAME" \
      --sku Basic \
      --admin-enabled true \
      --output none
  fi

  # az acr build builds in Azure, not locally. That matters on an Apple Silicon
  # Mac: a local `docker build` produces arm64 images and ACI runs amd64 only,
  # so the group would come up in a crash loop with no obvious cause.
  for image in ingestion scrapers enrichment ui; do
    say "Building team9-$image (linux/amd64, in Azure)"
    az acr build \
      --registry "$ACR_NAME" \
      --image "team9-$image:$TAG" \
      --platform linux/amd64 \
      --file "$REPO_ROOT/$image/Dockerfile" \
      "$REPO_ROOT/$image" \
      --output none
  done

  say "Rendering container group definition"
  local server username password
  server="$(az acr show --name "$ACR_NAME" --query loginServer -o tsv)"
  username="$(az acr credential show --name "$ACR_NAME" --query username -o tsv)"
  password="$(az acr credential show --name "$ACR_NAME" --query 'passwords[0].value' -o tsv)"

  sed \
    -e "s|__LOCATION__|$LOCATION|g" \
    -e "s|__GROUP_NAME__|$GROUP_NAME|g" \
    -e "s|__DNS_LABEL__|$DNS_LABEL|g" \
    -e "s|__ACR_SERVER__|$server|g" \
    -e "s|__ACR_USERNAME__|$username|g" \
    -e "s|__ACR_PASSWORD__|$password|g" \
    -e "s|__TAG__|$TAG|g" \
    "$TEMPLATE" > "$GENERATED"

  # The generated file holds a registry password. It is gitignored; say so out
  # loud anyway, because it is the kind of thing that gets committed at 3pm.
  say "Wrote $GENERATED (contains a registry password — gitignored, keep it out of commits)"

  # ACI cannot update a running group in place; replace it.
  if az container show --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" >/dev/null 2>&1; then
    say "Removing the previous container group"
    az container delete --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" --yes --output none
  fi

  say "Creating container group $GROUP_NAME (a few minutes)"
  az container create --resource-group "$RESOURCE_GROUP" --file "$GENERATED" --output none

  cmd_status
}

cmd_status() {
  require_login
  local fqdn state
  fqdn="$(az container show --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" \
    --query ipAddress.fqdn -o tsv 2>/dev/null || true)"
  state="$(az container show --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" \
    --query instanceView.state -o tsv 2>/dev/null || echo "not deployed")"

  say "State: $state"
  if [[ -n "$fqdn" ]]; then
    cat <<EOF

  UI        http://$fqdn/
  API docs  http://$fqdn:8000/docs
  Signals   http://$fqdn:8000/signals.geojson
  Groups    http://$fqdn:8000/clusters.geojson

Give the scrapers a minute after first boot, then check:
  curl http://$fqdn:8000/stats

EOF
  fi
}

cmd_logs() {
  require_login
  local container="${1:-}"
  if [[ -z "$container" ]]; then
    for c in api scrapers enrichment; do
      say "--- $c ---"
      az container logs --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" \
        --container-name "$c" --tail 25 || true
    done
  else
    az container logs --resource-group "$RESOURCE_GROUP" --name "$GROUP_NAME" \
      --container-name "$container" --follow
  fi
}

cmd_destroy() {
  require_login
  say "Deleting resource group $RESOURCE_GROUP and everything in it"
  az group delete --name "$RESOURCE_GROUP" --yes --no-wait
  rm -f "$ENV_FILE" "$GENERATED"
  say "Deletion started (runs in the background)"
}

case "${1:-deploy}" in
  deploy)  cmd_deploy ;;
  status)  cmd_status ;;
  logs)    shift; cmd_logs "${1:-}" ;;
  destroy) cmd_destroy ;;
  *)       fail "unknown command: $1 (deploy | status | logs [container] | destroy)" ;;
esac
